version: '2'
services:

  testrpc:
    build: testrpc
    container_name: testrpc
    hostname: testrpc
    ports:
      - "8545:8545"
    volumes:
      - ./testrpc/db:/src/db

  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"
    links:
      - testrpc

  truffle:
    build: truffle
    container_name: truffle
    links:
      - testrpc
    volumes:
      - ./cargochain:/root/cargochain
      - ./ProofOfExistence1:/root/ProofOfExistence1
      - ./ProofOfExistence2:/root/ProofOfExistence2
      - ./ProofOfExistence3:/root/ProofOfExistence3
      - ./ethereum_voting_dapp/chapter3:/root/ethereum_voting_dapp
      - ./PillarToken:/root/PillarToken
      - ./truffle/app:/root/app

#  meteor-dapp-boilerplate:
#    image: ulexus/meteor:v1.4-build
#    container_name: meteor-dapp-boilerplate
#    hostname: meteor-dapp-boilerplate
#    volumes:
#      - ./meteor-dapp-boilerplate/app:/home/meteor/src
#    ports:
#      - "8081:80"
#    environment:
#      - METEOR_ALLOW_SUPERUSER=true
#      - ROOT_URL=http://localhost:8081

#  cargochain:
#    image: ulexus/meteor:legacy
#    container_name: cargochain
#    hostname: cargochain
#    volumes:
#      - ./cargochain/app:/src/app
#      - ./cargochain/app:/var/www
#    ports:
#      - "8082:80"
#    environment:
#      - METEOR_ALLOW_SUPERUSER=true
#      - MONGO_URL=mongodb://mongo:27017
#      - ROOT_URL=http://localhost:8082

  mongo:  
    image: mongo:3.4
    container_name: mongo
    ports:
      - "27017:27017"

  ethexplorer:
    image: settlemint/ethexplorer
    container_name: ethexplorer
    hostname: ethexplorer
    environment:
      - WEB3_RPC=http://localhost:8545  #http://abc.xyz.com:8545 for selectRpcAndRun.sh
    ports:
      - "8000:8000"

  ethereum_voting_dapp:
    build: truffle
    container_name: ethereum_voting_dapp
    hostname: ethereum_voting_dapp
    ports:
      - "8080:8080"
    volumes:
      - ./ethereum_voting_dapp:/root/app
    links:
      - testrpc

#  pillartoken:
#    build: PillarToken
#    container_name: pillartoken
#    hostname: pillartoken
#    ports:
#      - "8081:8080"
#    volumes:
#      - ./PillarToken/build/contracts:/usr/src/app/build/contracts

#  truffle-init-angular:
#    build: truffle
#    container_name: truffle-init-angular
#    links:
#      - testrpc
#    volumes:
#      - ./truffle-init-angular:/root/app
#    ports:
#      - "3000:3000"

#  truffle-webpack-demo:
#    build: truffle
#    container_name: truffle-webpack-demo
#    links:
#      - testrpc
#    volumes:
#      - ./truffle-webpack-demo:/root/app
#    ports:
#      - "3000:3000"

#  truffle-init-webpack:
#    build: truffle
#    container_name: truffle-init-webpack
#    links:
#      - testrpc
#    volumes:
#      - ./truffle-init-webpack:/root/app
#    ports:
#      - "3000:3000"

#  ethereum-metacoin-client:
#    build: truffle
#    container_name: ethereum-metacoin-client
#    links:
#      - testrpc
#    volumes:
#      - ./ethereum-metacoin-client:/root/app
#    ports:
#      - "3000:3000"