version: '2'
services:
  ethereum_voting_dapp:
    build: truffle
    container_name: ethereum_voting_dapp
    hostname: ethereum_voting_dapp
    ports:
      - "8080:8080"
    volumes:
      - ./ethereum_voting_dapp:/root/app