version: '2'
services:

  testrpc:
    build: testrpc
    container_name: testrpc
    hostname: testrpc
    links:
      - netstats
    ports:
      - "8545:8545"
    volumes:
      - ./testrpc/db:/src/db

  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"

  truffle:
    build: truffle
    container_name: truffle
    volumes:
      - ./cargochain:/root/cargochain
      - ./ProofOfExistence1:/root/ProofOfExistence1
      - ./ProofOfExistence2:/root/ProofOfExistence2
      - ./ProofOfExistence3:/root/ProofOfExistence3

  meteor-dapp-boilerplate:
    image: ulexus/meteor:legacy
    container_name: meteor-dapp-boilerplate
    hostname: meteor-dapp-boilerplate
    volumes:
      - ./meteor-dapp-boilerplate/app:/src/app
      - ./meteor-dapp-boilerplate/app:/var/www
    ports:
      - "3003:3000"
    environment:
      - METEOR_ALLOW_SUPERUSER=true
      - ROOT_URL=http://localhost:3003

  cargochain:
    image: ulexus/meteor:legacy
    container_name: cargochain
    hostname: cargochain
    volumes:
      - ./cargochain/app:/src/app
      - ./cargochain/app:/var/www
    ports:
      - "3002:3000"
      - "8080:80"
    environment:
      - METEOR_ALLOW_SUPERUSER=true
      - MONGO_URL=mongodb://mongo:27017
      - ROOT_URL=http://localhost:3002

  mongo:  
    image: mongo:3.4
    container_name: mongo
    ports:
      - "27017:27017"